language: dart
dart:
  - stable
  - dev
with_content_shell: true
script:
  - pub run test:test -p content-shell test/test.dart
  - pub run test:test -p firefox test/test.dart
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start