name: dart_orm_adapter_indexeddb
version: 0.0.2
description: >
  IndexedDB adapter for DartORM
author: Ustimenko Sergey <ustims@gmail.com>
homepage: https://github.com/ustims/DartORM-IndexedDB
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  dart_orm: ">=0.0.4 <0.3.0"
  pub_semver: ">=1.2.0 <1.3.0"
dev_dependencies:
  test: ^0.12.5
